spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usersDB
    username: postgres
    password: nikita228
  jpa:
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update),production set to none or comment it
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

security:
  oauth2:
    client:
      clientId: 1708aacd6f7de758a8cf
      clientSecret: bde7ceace2af0cfb72be82a9552f43e5f5824934
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: false